services:
  silo:
    image: silo:integration
    container_name: silo-integration
    environment:
      S3_ENDPOINT: http://silo-garage-integration:3900
      SILO_PUBLIC_ORIGIN: http://127.0.0.1:3302
    networks:
      - integration

networks:
  integration:
    name: silo-integration
    external: true
